from PlotSetup import Colors, Markers

# We organize certain data series into one group, they are revalent and can be plotted into on figure. 
# Same group of data series must have close ylim, same periodicity, etc
PickEmploymentGroups = {
    'Name': 'Employment',
    'Periodicity': 'M',
    'Groups': [
        [
            {'ID': 'LNS11000000', 
            'EnglishName': 'Civilian Labor Force (K)',
            'ChineseName': '全美劳动人口（千人）',
            'Unit': 'K',
            'Color': Colors[0],
            'Marker': Markers[0],
            'XLim': None,
            'YLim': [150000, 200000],
            'YAxisPos': 'left',
            'Curve': None},

            {'ID': 'LNS12000000', 
            'EnglishName': 'Civilian Employment (K)',
            'ChineseName': '全美在业人口（千人）',
            'Unit': 'K',
            'Color': Colors[1],
            'Marker': Markers[1],
            'XLim': None,
            'YLim': [150000, 200000],
            'YAxisPos': 'left',
            'Curve': None},      

            {'ID': 'CES0000000001', 
            'EnglishName': 'Total Nonfarm Employment (K)',
            'ChineseName': '非农就业人口（千人）',
            'Unit': 'K',
            'Color': Colors[4],
            'Marker': Markers[4],
            'XLim': None,
            'YLim': [150000, 200000],
            'YAxisPos': 'left',
            'Curve': None}
        ],

        # Group 2
        [
            {'ID': 'LNS13000000', 
            'EnglishName': 'Civilian Unemployment (K)',
            'ChineseName': '全美失业人口（千人）',
            'Unit': 'K',
            'Color': Colors[2],
            'Marker': Markers[2],
            'XLim': None,
            'YLim': [150000, 200000],
            'YAxisPos': 'left',
            'Curve': None},                

            {'ID': 'LNS14000000', 
            'EnglishName': 'Unemployment Rate (%)',
            'ChineseName': '失业率（％）',
            'Unit': '%',
            'Color': Colors[3],
            'Marker': Markers[3],
            'XLim': None,
            'YLim': [3, 10],
            'YAxisPos': 'right',
            'Curve': None},  
        ],

        # Group 3
        [
            {'ID': 'CES0500000002', 
            'EnglishName': 'Total Private Average Weekly Hours of All Employee (Hours)',
            'ChineseName': '私有部门平均每周工作时间（小时）',
            'Unit': 'Hours',
            'Color': Colors[0],
            'Marker': Markers[0],
            'XLim': None,
            'YLim': [20, 40],
            'YAxisPos': 'left',
            'Curve': None},

            {'ID': 'CES0500000007', 
            'EnglishName': 'Total Private Average Weekly Hours of Prod. and Nonsup. Employees (Hours)',
            'ChineseName': '私有部门生产非管理人员平均每周工作时间（小时）',
            'Unit': 'Hours',
            'Color': Colors[1],
            'Marker': Markers[1],
            'XLim': None,
            'YLim': [20, 40],
            'YAxisPos': 'left',
            'Curve': None},

            {'ID': 'CES0500000003', 
            'EnglishName': 'Total Private Average Hourly Earnings of All Employees (USD)',
            'ChineseName': '私有部门平均时薪（美元）',
            'Unit': 'USD',
            'Color': Colors[2],
            'Marker': Markers[2],
            'XLim': None,
            'YLim': [20, 40],
            'YAxisPos': 'right',
            'Curve': None},

            {'ID': 'CES0500000008', 
            'EnglishName': 'Total Private Average Hourly Earnings of Prod. and Nonsup. Employees (USD)',
            'ChineseName': '私有部门生产非管理人员时薪（美元）',
            'Unit': 'USD',
            'Color': Colors[3],
            'Marker': Markers[3],
            'XLim': None,
            'YLim': [20, 40],
            'YAxisPos': 'right',
            'Curve': None}
        ]
    ]
}

PickProductivityGroups = {
    'Name': 'Employment',
    'Periodicity': 'Q',
    'Groups': [ 
        # Group 1
        [
            {'ID': 'PRS84006092', 
            'EnglishName': 'Business - Labor Productivity (Output per Hour), percent change from previous quarter',
            'ChineseName': '商业 - 劳动生产率（每小时产出），季度环比',
            'Unit': 'quarter over quarter (%)',
            'Color': 'r',
            'Marker': Markers[0],
            'XLim': None,
            'YLim': None,
            'YAxisPos': 'left',
            'Curve': None},

            {'ID': 'PRS84006112', 
            'EnglishName': 'Business - Unit Labor Costs, percent change from previous quarter',
            'ChineseName': '商业 - 单位劳动成本，季度环比',
            'Unit': 'quarter over quarter (%)',
            'Color': 'r',
            'Marker': Markers[1],
            'XLim': None,
            'YLim': None,
            'YAxisPos': 'left',
            'Curve': None},      

            {'ID': 'PRS84006152', 
            'EnglishName': 'Business - Real Hourly Compensation, percent change from previous quarter',
            'ChineseName': '商业 - 实际每小时报酬，季度环比',
            'Unit': 'quarter over quarter (%)',
            'Color': 'r',
            'Marker': Markers[2],
            'XLim': None,
            'YLim': None,
            'YAxisPos': 'left',
            'Curve': None},

            {'ID': 'PRS85006092', 
            'EnglishName': 'Nonfarm Business - Labor Productivity (Output per Hour), percent change from previous quarter',
            'ChineseName': '非农商业 - 劳动生产率（每小时产出），季度环比',
            'Unit': 'quarter over quarter (%)',
            'Color': 'g',
            'Marker': Markers[3],
            'XLim': None,
            'YLim': None,
            'YAxisPos': 'left',
            'Curve': None},                

            {'ID': 'PRS85006112', 
            'EnglishName': 'Nonfarm Business - Unit Labor Costs, percent change from previous quarter',
            'ChineseName': '非农商业 - 单位劳动成本，季度环比',
            'Unit': 'quarter over quarter (%)',
            'Color': 'g',
            'Marker': Markers[4],
            'XLim': None,
            'YLim': None,
            'YAxisPos': 'left',
            'Curve': None},  

            {'ID': 'PRS85006152', 
            'EnglishName': 'Nonfarm Business - Real Hourly Compensation, percent change from previous quarter',
            'ChineseName': '非农商业 - 实际每小时报酬，季度环比',
            'Unit': 'quarter over quarter (%)',
            'Color': 'g',
            'Marker': Markers[5],
            'XLim': None,
            'YLim': None,
            'YAxisPos': 'left',
            'Curve': None},

            {'ID': 'PRS30006092', 
            'EnglishName': 'Manufacturing - Labor Productivity (Output per Hour), percent change from previous quarter',
            'ChineseName': '制造业 - 劳动生产率（每小时产出），季度环比',
            'Unit': 'quarter over quarter (%)',
            'Color': 'b',
            'Marker': Markers[6],
            'XLim': None,
            'YLim': None,
            'YAxisPos': 'left',
            'Curve': None},

            {'ID': 'PRS30006112', 
            'EnglishName': 'Manufacturing - Unit Labor Costs, percent change from previous quarter',
            'ChineseName': '制造业 - 单位劳动成本，季度环比',
            'Unit': 'quarter over quarter (%)',
            'Color': 'b',
            'Marker': Markers[7],
            'XLim': None,
            'YLim': None,
            'YAxisPos': 'left',
            'Curve': None},

            {'ID': 'PRS30006152', 
            'EnglishName': 'Manufacturing - Real Hourly Compensation, percent change from previous quarter',
            'ChineseName': '制造业 - 实际每小时报酬，季度环比',
            'Unit': 'quarter over quarter (%)',
            'Color': 'b',
            'Marker': Markers[8],
            'XLim': None,
            'YLim': None,
            'YAxisPos': 'left',
            'Curve': None}
        ]
    ]
}
